version: '3'
services:
  public:
    build: ./public
    volumes:
      - ./shots:/shots:Z
  app:
    environment:
      - GMAIL_ADDRESS=${GMAIL_ADDRESS}
      - GMAIL_PASS=${GMAIL_PASS}
      - MAGIC=${MAGIC}
    build: ./app
    depends_on:
      - db
    volumes:
      - ./shots:/shots:Z
  db:
    image: mongo
    volumes:
      - ./db:/data/db:Z
