version: '3'
services:
  public:
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    volumes:
      - ./public:/public:Z
      - /public/node_modules
  app:
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./app:/app:Z
      - /app/node_modules
  db:
    ports:
      - 27017:27017
