version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - 8000:80
    depends_on:
      - app
  app:
    environment:
      - NODE_ENV=production
      - PORT=3001
    command: >
      sh -c 'npm run build &&
             npm start'
